### PR TITLE
Some fixes, some changes

### PR DESCRIPTION
**Pull request by aivoprykk**
Fixed:
OTA_Server firmware upload page javascript.
GPS_Data changed BUFFER_SIZE from 10000 to 9500 as for fitting into 1.5M Image partition.
Some compiler errors about types.

Changed:
E_paper>
-Display unified row heights macros, changes in screens accordingly
-ESP-GPS logo size to 24x24
-Moved time, gps and battery for all screens to bottom row infobar.
-New screen for GPS initialization.
main.cpp> Ublox initialization moved after Wifi connections closed.

New:
Partial code for OTA autoupload, dev status yet.
M9 15Hz support
Added support to PlatformIO and partially for ESP-IDF (CMakefile.txt), thats why Rtos.ino moved to main.cpp. Wrapper module: https://github.com/aivoprykk/ESP-GPS-Wrapper

### CODE REVIEW

**Comment by aivoprykk** [comment]
PlatformIO wrapper: https://github.com/aivoprykk/ESP-GPS-Wrapper

**Comment by RP6conrad** [comment]
Thanks for contributing to the project !
Some questions : 
Until now, I used Arduino IDE 2.02, and ESP32 1.06 library. I tried to update to ESP32 2.09, but I had a lot of issues with this update (runtime crashes with E-paper functions). Which ESP32 library are you working with ?
Is it easy to adapt the project to Platform IO ?
Greetings, Jan.

**Comment by aivoprykk** [comment]
Hello! First i tried also Arduino ide 2, but could not build. Arduino is simple, debugging is limited and so on. Then i managed to set up esp-idf (https://github.com/espressif/esp-idf.git (detached at origin/release/v4.4 because of arduino-esp32)) and arduino-esp32 (https://github.com/espressif/arduino-esp32.git) as component. Environment is PlatformIO and VSCode. Also tried from ESP-IDF directly, much more debug output, but really firmware not working on device. PlatformIO is easier to setup. Also i created custom partition layout required for ota. Default esp32dev target has defined 4M memory, this limit is not upgraded yet to Lilygo 16M.

**Comment by aivoprykk** [comment]
PlatformIO dir structure is different, there should be src folder in in project folder, that's why the another project https://github.com/aivoprykk/ESP-GPS-Wrapper is there for implement PlatfomIO requirements. ESP-IDF dir structure is similar to PlatformIO.

**Comment by RP6conrad** [comment]
I could merge your changes succesfully. Some quesstions : 

- When compiling again with Arduino, I have a compile error with the main.cpp file (Rtos.ino not defined), so I did removed it.
- What is the idea of  : 
- #if defined USE_AUTO_OTA_UPDATE
          if ((millis() - OTA_CHECK_INTERVAL) > _lastOTACheck) {
            _lastOTACheck = millis();
            checkFirmwareUpdates();
          }
I don't see the need for checking it on millis() interval. Probably "Work in progress" ? It make sense to do this on monthly basis or so.
Greetings, Jan.

**Pull request merged**
